<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\NoviBet.Domain\NoviBet.Domain.csproj" />
    <ProjectReference Include="..\NoviBetConsole\NoviBetConsole.csproj" />
    <ProjectReference Include="..\NoviBetInfrastructure\NoviBetInfrastructure.csproj" />
  </ItemGroup>

</Project>
